# Generated by Django 5.2.10 on 2026-02-03 02:40

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='テナントコード')),
                ('tenant_name', models.CharField(help_text='企業名や団体名', max_length=100, verbose_name='テナント名称')),
                ('representative_name', models.CharField(help_text='企業や団体の代表者名', max_length=100, verbose_name='代表者名')),
                ('email', models.EmailField(error_messages={'invalid': '有効なメールアドレスを入力してください。', 'unique': '同じメールアドレスが既に登録されています。'}, max_length=254, unique=True, verbose_name='メールアドレス')),
                ('tel_number', models.CharField(blank=True, help_text='半角数字とハイフンのみ使用できます。例：090-1234-5678（任意）', max_length=20, null=True, validators=[django.core.validators.RegexValidator('^[0-9\\-]+$', '数字とハイフンのみ使用できます。')], verbose_name='電話番号')),
                ('postal_code', models.CharField(blank=True, help_text='ハイフンあり、またはなしで入力可能です。例：123-4567（任意）', max_length=10, null=True, validators=[django.core.validators.RegexValidator('^[0-9\\-]+$', '郵便番号の形式が正しくありません。')], verbose_name='郵便番号')),
                ('state', models.CharField(blank=True, help_text='都道府県名を10文字以内で入力してください。（任意）', max_length=10, null=True, verbose_name='都道府県')),
                ('city', models.CharField(blank=True, help_text='市区町村名を50文字以内で入力してください。（任意）', max_length=50, null=True, verbose_name='市区町村')),
                ('address', models.CharField(blank=True, help_text='番地などを100文字以内で入力してください。（任意）', max_length=100, null=True, verbose_name='住所')),
                ('address2', models.CharField(blank=True, help_text='建物名・部屋番号などを150文字以内で入力してください。（任意）', max_length=150, null=True, verbose_name='住所2')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='削除フラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('create_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('update_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updater', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'ordering': ['tenant_code'],
            },
        ),
    ]
