# Generated by Django 5.2.10 on 2026-02-09 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='削除フラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('product_category_name', models.CharField(help_text='100文字以内で入力してください。', max_length=100, verbose_name='商品カテゴリ名称')),
                ('create_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='作成ユーザー')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant', verbose_name='テナント')),
                ('update_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updater', to=settings.AUTH_USER_MODEL, verbose_name='更新ユーザー')),
            ],
            options={
                'verbose_name': '商品カテゴリ',
                'verbose_name_plural': '商品カテゴリマスタ',
                'ordering': ['product_category_name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='削除フラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('product_name', models.CharField(help_text='100文字以内で入力してください。重複登録はできません。', max_length=100, verbose_name='商品名称')),
                ('unit', models.CharField(blank=True, help_text='数量に対する単位を20文字以内で入力してください。例：個、箱、kgなど', max_length=20, null=True, verbose_name='単位')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='数値で入力してください。小数第2位まで指定できます。（任意）', max_digits=12, verbose_name='単価')),
                ('description', models.TextField(blank=True, help_text='商品の仕様や補足情報などを255文字以内で記入できます。（任意）', null=True, verbose_name='商品説明')),
                ('create_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='作成ユーザー')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant', verbose_name='テナント')),
                ('update_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updater', to=settings.AUTH_USER_MODEL, verbose_name='更新ユーザー')),
                ('product_category', models.ForeignKey(blank=True, help_text='商品のカテゴリを選択してください。（任意）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.productcategory', verbose_name='商品カテゴリ')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品マスタ',
                'ordering': ['product_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='productcategory',
            constraint=models.UniqueConstraint(fields=('tenant', 'product_category_name'), name='uq_tenant_product_category_name'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('product_name', 'tenant'), name='uq_product_name_tenant'),
        ),
    ]
