# Generated by Django 5.2.10 on 2026-02-09 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['sort', 'product_category_name'], 'verbose_name': '商品カテゴリ', 'verbose_name_plural': '商品カテゴリマスタ'},
        ),
        migrations.AddField(
            model_name='productcategory',
            name='sort',
            field=models.PositiveIntegerField(default=0, help_text='小さいほど上に表示されます。', verbose_name='表示順'),
        ),
    ]
