# Generated by Django 5.2.10 on 2026-02-04 13:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='削除フラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('partner_name', models.CharField(help_text='100文字以内で入力してください。', max_length=100, verbose_name='取引先名称')),
                ('partner_name_kana', models.CharField(blank=True, help_text='全角カタカナ100文字以内で入力してください。（任意）', max_length=100, null=True, verbose_name='取引先名称（カナ）')),
                ('partner_type', models.CharField(choices=[('customer', '顧客'), ('supplier', '仕入先'), ('both', '両方')], default='customer', help_text='取引先の区分を選択してください。（顧客・仕入先・両方）', max_length=20, verbose_name='取引先区分')),
                ('contact_name', models.CharField(blank=True, help_text='50文字以内で入力してください。（任意）', max_length=50, null=True, verbose_name='担当者名')),
                ('tel_number', models.CharField(blank=True, help_text='半角数字とハイフンのみ使用できます。例：090-1234-5678（任意）', max_length=20, null=True, validators=[django.core.validators.RegexValidator('^[0-9\\-]+$', '数字とハイフンのみ使用できます。')], verbose_name='電話番号')),
                ('email', models.EmailField(error_messages={'blank': 'メールアドレスを入力してください。', 'invalid': 'メールアドレスの形式が正しくありません。', 'null': 'メールアドレスを入力してください。', 'unique': 'このメールアドレスは既に登録されています。'}, help_text='半角英数字で正しいメール形式を入力してください。例：info@example.com', max_length=254, verbose_name='メールアドレス')),
                ('postal_code', models.CharField(blank=True, help_text='ハイフンあり、またはなしで入力可能です。例：123-4567（任意）', max_length=10, null=True, validators=[django.core.validators.RegexValidator('^[0-9\\-]+$', '郵便番号の形式が正しくありません。')], verbose_name='郵便番号')),
                ('state', models.CharField(blank=True, help_text='都道府県名を10文字以内で入力してください。（任意）', max_length=10, null=True, verbose_name='都道府県')),
                ('city', models.CharField(blank=True, help_text='市区町村名を50文字以内で入力してください。（任意）', max_length=50, null=True, verbose_name='市区町村')),
                ('address', models.CharField(blank=True, help_text='番地などを100文字以内で入力してください。（任意）', max_length=100, null=True, verbose_name='住所')),
                ('address2', models.CharField(blank=True, help_text='建物名・部屋番号などを150文字以内で入力してください。（任意）', max_length=150, null=True, verbose_name='住所2')),
                ('create_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='作成ユーザー')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant', verbose_name='テナント')),
                ('update_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updater', to=settings.AUTH_USER_MODEL, verbose_name='更新ユーザー')),
            ],
            options={
                'verbose_name': '取引先',
                'verbose_name_plural': '取引先マスタ',
                'ordering': ['partner_name'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'partner_name', 'email'), name='unique_tenant_partner_email')],
            },
        ),
    ]
