# Generated by Django 5.2.10 on 2026-02-08 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0004_alter_partner_partner_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='partner_type',
            field=models.CharField(choices=[('customer', '顧客'), ('supplier', '仕入先'), ('both', '顧客・仕入先')], default='customer', help_text='取引先の区分を選択してください。（顧客 / 仕入先 / 顧客・仕入先）', max_length=20, verbose_name='取引先区分'),
        ),
    ]
